table DimCommunity
	column community_key
		dataType: int64
		summarizeBy: none
		sourceColumn: community_key
		isHidden

	column community_code
		dataType: string
		summarizeBy: none
		sourceColumn: community_code

	column community
		dataType: string
		summarizeBy: none
		sourceColumn: community

	partition DimCommunity = m
		mode: import
		source =
			let
			    Packed = Text.Combine({"bZhPk7O4EcbvUzXfwR9AyQx4xn+OMsjAAoJXwvY6lxw2OaRS2b0kldpvn98jwJ7ZyuExUiOk7lar+5F/+e1f//rPr//49+9//efffze/PHq//Pa3vz+7ry+Zec9OwutLzqMQXl+2PM7C68sHj1p4ffnk0QqvLzvznp+E15c9j0J4fTnwcMLry5HHWWCJd56tQJv18k6gzYLbm0CbFT9LgTZLfjqBNmt+ngXaLPpZCbRZdWcF2iy7Owm0WXdXCNjDusdSoM26x1qgzbrHQaDNusdRoM26xx8C7U+TvZcC7R1PJ9Demwx/ZclfB5PlVqB95HkScN47z0KgnfH8SaCd82wF2luenUD7w2TbQqDNulsn0Gbd7VmgzbrbSqDNuttaoM2620Zgp1h3+5NAm3W3vUCbdbdeoL019nQS3L20Hat8fNAbjb2EIdjN6RIb72LcjDag5scnL4Ox/alzoSkrjd8ZW1ihbDD8Y29sdxJcmNJXb4E3MQ5+U7umqqfIoAMDRoHJ16mP9CfBlkNg4s93Y8dR6NxtGMpl3GdmbDgJwyVsOttqaG5sHAXnNxrLGp9YdjkJl+A3J3tHhGl36Xaf6rfT4P39FIZBc36aUzkYRPbaxMluyuHmNcfOnFwplI2vpq8mfO4Rd8KfbJPUPZhT10vQD36if6Tv1Z86rOSIvJuTP5uT9efzZgq2Yat3GbJWsvbaOOJ+l6PFTZDX6W/NKVjBxabULB90UCl5v7O+fAvN1YXlJXYEJ/hJbkCy09A0fPYiIjQPk0ST9V57tkP1SxB83DS+vMQpNFbqYcNV9ndXVzpZuceI+xWF77O++8wUtheYz37xzz5H6IU7busdm3qTeItoFJpp6DZ107HM/gNBEMLsZkSfdKMwPSJtvzMFuwHYfByCZG+Kig+HS2XDZh12MEVtBQImyIz9kV4LGs92L3F0eEfgk9BOuBsJttRBIAaaNS4PGFJftYafwj1pHDdXfq0WO2BPfdNioXNxdvABcxoUsB1a3XHo5AJrNERXtyFYxiEQHwcsbCbBlg4lD1jXNQLhcbr4ynYDDj5goscRQ/DsMr7Rolg4WKGoFxceMHHoBIKtmvU4YuEgX3tb2s3Q3fuxKRarjpmmFNApjvI7u3PMZed3W5Fi4yAPXN03MWaOZy0xunBuXKclMYpwBT6mfTxiFREJYsHXz/g4Ylfo04tpPjBHrIqFHHKPxIdqBkYRlyCwHSftZtFGFZB3Q7IS6oEEpbrwnpnyVJjSocswTM/EpWVDGpGbsqxMSbB0NirZvVWd83qzNeQuAU3KjQyV9ANJFCTA7iW+svdPU3qWImgUOIzvexfY8o7mvNSOEe45whHGz5jJ3ve8vj1f3/DBxnmVuvcD4qvggrpHU4YqWfVYnvJZBr/ILtKfIupsJXTuOSxHcBE2RTenqIyq6nABcLPPM2qrOzdGCi5bmFFi3fmaRJszH+qgf8sKGYXXja1xHWlqiaeMAsw5FR4ZOKMQu9AJKRYyirGL9TxzrB1flt8npkK7qxNCFVzaGwq1u3qwRlRGuXZ3m1a/q9pTslHTrKpK8kGvE4rBr/6ggp9rhhEcSwBnFPJzPSFSED5DM6Oon7tmlXeWLfqu5oH3/ut7CY/mjFPOTaw3RLVb80xG+T9zJoBvOZySZOZ8fWr8fXJYQcVmVkqGKpqrI2AIlb095auTYQvVqTUK5aWaZZCGihIuUYqSPxTxDCJRld38PtX8DDrBoRD6IVQ2rXegGyQqmi/RB8GoRmfQylLeCSxKhjZUNO2dV823V5JmSGf9mHvNqhkkhIEmWSdT3lJLRURxDy2pQjO//YOLHhNgd7g+h0iE3RNfDV0JD9BoXyXz4Cg1VQqMxFDSak8vCNe090tEQExqnAzaOYdm0JLa3oV4GsIgBvpu6qYUtMrVdp27S5whOoOqXk8StISJha6+hOQjWEnd3NKoZQFISd1GUw8TNapRzc+gIzXJGTR/SSEPDyHRCT6myddgfUsOW2pABiepcbUmFzNYPQUzqSMKDz2mUoglwqrosSq29q6SksFO6osXppXqLD6Bo9SXn4XZUCgKI4SVUWSwlBYO2DZeBUWCD9PCjsC1UQjPGRV60uKPVomQcnZP+VcBnabd6XuhitJeor1pyRetu6fC99ToYDp3ArcmQlpE/2EqnasEW2g2eErXXAXNNycOuErX8hmUcfOgepLnyK9JvgQSLKXrg6EAE/m9quEmkGzkY7hKh487mdr51cXQld4WgrvBgpa6AmHp7RncddQl2NOphYFDlvQ80Os0JO3YMwfBWXr4EyhqbZs+h7L0RQOgFtIFwtIXreD8X6iQMxnOYCx9MT3FqjFJvjV9yequbIpmcafEH4ismSkaG/NIXDAU6prQUBplEBylJ/SBt+Nc6uAnPVUSxCZ5GXLSkzwXiyTAEhJJz2pkLn0DMel988W27xkQbkJ1EqaKmE3RATPp4TLzXnAhsNGm+gU3IauksfDT+6o63KRnl3pYmU7tpaofbzBqlMPHL7USltKH7utwCbEsSA2oevIfBKWHODOKI7IkTiiKf1vvfNCSudOqk6UOUCc3nrziYX61KOCNdCLx1ngC2ZPgOMjsvDyYQzx81S+D/5A3c8iHry/Ly9pCyTYXETC92vHq+vWVhHsEnWD9suM5JMPjHT/EOQgecx/NYFthcUwO1xiqUkiTQTSGsTYDhNHd19kgGgOnNI2hrA+jLINpjMQ16NhzaQfTGAlogEN7ux7mHLox2klgB2NyAPxiJK7T5TCVUsn2ZuSAAxsv6bsDHS+ksueed4wcnsG36fvVEJjF2JZGhs47l0MsxrZOksUQiMXYdkkyh24OtRiHRiDqOE+6ROawi/HSC+PqArjFj640Py7Uorh+uzM/cPIsSx5+MsAchoEThDjPeaDthSKlblkBoQh4IQwx6mY0FHIDZCJQuhG6xQ7IROBWBDYMG90kWU7fC+eghJZDHkJTCLUoriQf9EpBDHEJAIgDt0mTbpQnN4/bmdBPacGZMuZwBZQR2gcnzmELYfhZmKtkDk8gZZqUNjdElP5OQfeQlID4DZtkrMQYEKVsuVxvcrgBxFYok4mwgXCZhC9lLYcAhOtNPquWvJ1DAAK303nRJb3nFP/IRkZX6Aq2ybeS7U20pVA+00BO9SetCLMqj+KewwIi5zcOl2/nFyrA3ghhMRsWwEVH8Ny1rK43kuYmloWJGITRWupTCk1CinhIQDzXy/xfKGoOFYgVLwibNdggA7HqTNKwspPSvtffE3qFWXUFLOXFjmMjGUbBe/8f386hAZE7MOPT3w2yFB4Q67iI3CZ2w5hMgAVELrpME+ain8MDYlMJutcuysEEIiUeEELPi2UOIYgtfmnv+jNkYYw5hCC2QdJE8taIgArE9vYYrOuRpBjnrZyo/4gkwDICcXbactuWGKOGXiCfpOMAGYhcqtLAJVLgAnFYNnSxBxoQSW6zzvpHZrUJNoBQuBQkJF3QJcUiKOrXEPruXDhBhHahr7/Pf8/kEIIYb494eVtsWS2EHsQpm3f2vskkwcQpXyW5JFg3bVeJYhlWEKePVfIhiebAU9OfN4QGGSA+iUV+0HSlBqyX9vyg+dxTtG7PQbMGwU41Vym7Hj2YAaoL69GBGcTrsOw7eVgirLny9Z28EZej9NhiWAKrCXbJY9CEyfXCmPqQhKkehOCTz5MwQxDNdGv8ekJgBtMlCkWiVDmUYIKvAkeWWTSGEFxgdKlUfmd0OYyAcwnm/9Gm+4YrP5tYyAUwA158ffn0JAThQvx9eTecv8QhdOHy6z9//e2/v65PCY/mCiWcvbH4fwtvQGBWF80u3UIgrrgIaG4JckNOM/M/lA81tpCIG1+DVKS30IfbyRtF9SkRly2cgQgT5LgyfbQzt2pKIuUQSfbmRp4Ak5PPJTrQ7dKgzZdLzBaecOOQg+7xB8AWqsDkQvzyR+lb8vV86LbQhxtlku/K+cxt4Q43LwlaDeEx1VbaJwuWYriFPdziOKvyyCpbuMPtpoHdeTNrI+HO3KHz9yG0KrjY9j8="}),
			    Source = Csv.Document(Binary.Decompress(Binary.FromText(Packed, BinaryEncoding.Base64), Compression.Deflate), [Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Blanks = Table.ReplaceValue(Headers, "", null, Replacer.ReplaceValue, Table.ColumnNames(Headers)),
			    Typed = Table.TransformColumnTypes(Blanks, {{"community_key", Int64.Type}, {"community_code", type text}, {"community", type text}}, "en-CA")
			in
			    Typed
