table DimService
	column service_key
		dataType: int64
		summarizeBy: none
		sourceColumn: service_key
		isHidden

	column service_name
		dataType: string
		summarizeBy: none
		sourceColumn: service_name

	column agency
		dataType: string
		summarizeBy: none
		sourceColumn: agency

	partition DimService = m
		mode: import
		source =
			let
			    Packed = Text.Combine({"rV1bc+O6kX7fqv0PrHnYnFMlx6J4kfQoyZdxRbYVUx5nn7ZgCZYYU6TCiz3Or99uXHkXKechJzM2vg8g0N3objQwCY0//A39v3f6NUjEn0NyoAOyo+Hm67//yxzMFqulcWHMQv9AAmMJLcINhR/chf/K/NinyWDhwV+vDzRmGOOehIA+0DA1SLg1FtHhkIV++mV45I2mwDmSnHM/pcYqph/Q1o9C+GO0i8nBmB2Pgb8h+LPe5JYkX0YJb3MTZfBfPv7edLake4jgt8DoHcmXEcXGA81SGqshnz8bjuzhxU+o8bL3k3caJ4ax3vvhO8z3OzWI4W18nCPofxGQJDH+5qe9O3IHM08vJM59b4pxgWKxJwlKwnofU9J/PJMC2RU5kJ0f7owVTXF+YWKPNE6/etNOC7R34T+zmG57s5jDEg0s9huNUfb7c5kFrocIFro/yahAsiLxO/xtRdL9JwjkIoKBxWF/6TOtIm32CppnPNGAad8ZfHaBz+M2JTFmSQLSS9B0PFFUlXPWxClwr2m6hxXZGhdr/xy2oj78ont/E1Dj8e0NF/mMLy8qB0mNJQFsfx6hF1fRzriib/RMO2gKPbj+DR+TMK0SQtLfXg8rVCsaH84wQSOhCT+zAwm5bvZX8JHQhKX/QZM02ryzdnM/3v6R/Gn4oQFiYSz8M0zHSCgDs/VhGkcBWwWgBKkwlpQke2MGtq4/sdCKlQ+jfT4aXhqTM4Yn5B9M4xssBEgFYQP8JME7bkVnronQgyeQWM/f7VMwwv1JhPA/hwE6CAk9e8MdCfF/jl9BRPQaLzlvwmD8U8/wPEAp1gD5Y7Werf5Ue4yxJr/zFqq4qcNCrW6YZifQf6LoAQTuxpAz8t/BZ/8iQUZbEWYewX53S0Mas13mdH+jClp9xRVNiR8krXCLw+d3M/7Rmw14R2mnnm0BXd+tVsZsF1M+02jOYY1aoQ6HPj4s7x6ui9N+FW2yzjxugYcN5C58i+IDs5GdKMacotekTUqYvjM3rcHP/SBgTbyUpJ1n0h7WUN2FHxFoB5f5PW46XUZlmzVUK/LFWs22/8ySFP+YSITUitapsoV4ept9BNbTy47HKE7BoKY4wD5rbQtJ7S9tthDU/CrdEx88uJAw960FCoL6hm79zygDH3wdkzDxU2gsNVT5WY9IsSDBjsRfsh3g3QFqlhiksE/gqqWATvb+MYEm48E8S/wQd1JullCn5E9keCX6QbN87/UPWiaD+VdAPvErtx/RhgAITHt4vptoTxXjnH5F0AY32TnZ7rS1VEvTNwAaKu4FCUPy6ifnD9QxFdkVmPMMdxGhGnO6Jx8+LGx+HXvzjxT/MoJo5TbGcAyCN0q3CRqjmGzO8tccSxHfg0GIfRglhsTcIT87GnJsRcvijm98uaOY+ParKK9/08PxvI92Nac0QzlV/cZgx5r4uyGNo7XJC6NP1uoOBger4/lbit5Xf06tT94RdoJvSLyr1WcNVhIZ93H2+h1ZdLUS/YIWJPCTA/e71K6J0fo31sfVaiQDr/O5tOa8kCTlyv5EN1+bAPMJeh7OoLZz1Lgv3PtJBhJ/yXpC9nNjKtcpMatI+Vwz6rqDxeyOmfxtjOEB+3buBvxY3TG6RRQE5DWKeUgJLjoJvmBn5nv8XRhGH+w3P4BtLNjmAXrfGHL4Af0O4UQQYmRmPEKcEFJGwOfvDMJpLeENGOJXAkO+AbcQf3zOYMdDwX0d0A3EgSEYkCuSErU4Z1CagvL2zoPFPB5xfQhLTAIGQo9vzO14BNyPCNn79A0E4OCHsPkBMor/kmDwit6X5F8uPa++rWwKjNZgcY3fH3748Pkodio+wSTn6opRBBDiCYXLtQS4zeFP/pHATsb8GIjkcDN+78HicJY1phd5qBMQ+O8anbOTYJeDuXbN42izz2J6EjXOo0A4MSlO8snp0x1P8hRPIC2xL8zPKeQ0h0z2dHsKMAExvb6fsY04zNmKc03IBGT05gow5nCY7jGlku63BH6fxcdYJS2l13vjxyApk5HAzDM/2KJQ+2Ku0J+9C5MjZV+PqvlzXstgKYaSF9wJbQt0+XPKKfkSzNGwI8wvi3QujfUeJfR/owz+DFtItANCtYOWGFzBgH8Fmi01fpJ/k3jLKdGLaRn1uALGJSkmAmDoLQyTPIP4ZNQPGPeHTz9bkNM6JCwXKnnT106HBRBvyDSxtrWZb72OM7DH8yh6V6mlUvNRrvlnFL8nxuorjozHIw2Nm4AcINQIxIbbRSamUqJgQUBz2iVhKgXoLtyAO8diTBa0FrSohHEUhofeKt6uaSvlZMmifUrizT7v7/Kf1CKlkCz9N7VQ3he4OIdumjWVMrKEPfw1+i2H2YKYlhDC6h1w6qOYZS0qbk+RAmyH4ABniScCw4zJ9OkBm0MpOPfRK/obN1G05Z2xfGdHEilOj5tNdsQdYxmRbUesFB1QiItVBiuDZ1wAhbCxaJJaOGzFEX34IFW5c9Nug5DiJWKX2dsb8eOkXY7NoRQ0IbhGGhkkhVBqaxCuiFcxJp1a+pUC5y1+Pj4u86BPHzYEEAr4lIIFkMm4ej4pfyi7mFNhTmlL/1L6vEP0To1ZQOJDwRbOkiT9q/EWobsc+uCwXEKQT14DefxT4jOlJHow57gK1x/MzndaBFOK4po7LV0gUvDWdLMHnzF/AHbKKpsmSN5PdOJgtaN4i18lpwx2ee3dyWmUrppp2i1ArwUHUrYqbJy4fYR8iSo7kfRFKo2RyeVMd+GWHkL/TZzd67RdO3rM0ULYWbwGTlO2ScFhU5a1jWDCCZ7oxTMoa/RmXP/2+W7hYYWBXINWjinn4F7bFf2gQXRkrlKHAYxAzlZzllSsxl53fK2PPnrQaoZZQkrlAcUAkcqUVPPYx+waCFMWhhTV9hmmNz5ivkma357cI8m9CrLEMB3De/9i6YuePJbk4bPF97VPDI/B68HBbZnXlBOenh3YqgOw/+ADgLVB+4dLfMQ/9eUDSX9ioo4Lx9MDO358prCNAt8IQWJXEP8EeYtipvE/v7Yx7jksXgRLdRNEn2AQwJHoQgi64C20cfjrhuiIlsV9SZJR4aEMZKCYQecHnUPIe/dcE9kkTCR1FB8xqkSahLsjSsZ7EYLKsKOoLUR2qZ/IFSg2bMiUm9aQo+f+O1hH9CX5rxrbm6I9SO5TlMHo0R2Bv3gbiJSygDYCRxropdGxeUSWbgjcC/gNSLNMT+VPEJoIbE4gkCcH5hSbpycmzOXNWV2Tygc3NR7zxqxMhAkbuLYAxZBk+bQWc9eIngh0HP0TNr3mdkICCmlRcXLehLHFusuzlRXaMxVbN4HMIkj4wpdyz7hOfXB5wNdpJGBCMEPxn8Eu/oE6KNx8XICZcfewvn56mC0bCaw2AoJBnMDkmBb1VHYb1Z5u8DD/NIvTwuKBguwDtiIneVzFs479o7Y2bF4ap2PcjMpNRnOvk2a8mIE1+e0346eNePXtjWAHRFD8UPuk5TN4nk8rNkMsSCJO9SyDPS5ie1J15xAJN3BEZCmKbI8MI86wCCgGujVnizJBp1r9RSfmTMcqwe/R1vpH9G4D4aH+Hd1/DOTbmewSk0eDt4vbDCzFNsfKshn0N4/12wlBJMH2s+qWFDY35rIzB90PAHA527Awjv8NR04pc9L+B/1y4arqJI4iQWb3G8xh2s49ruGurEkrw2RQST5d1Bcm9EzImc60jppbPb5dnM/tghooVwBTvRty4C7v+dWErlngvI0JCEfqf4dxNDjtsFimKbLiCVYw4aK41uBqzh1pmZjEdC6LK3BJ5IgETqruD+6k5QKAgXYpuX8p2KR/+QM7s2VnLJWnM/lnkTmSTM8TP4dg/iWmJSEg4Cd7Z/bgyh5WTwsjl4uS83su71jx5l3yfDSFUaousPCezu1pInt6urv/T37BVPJ6V3hY8wAhu5e9bmF/Zfkn9Kfy+YMzuxkP27vxsviNFLJF53ZkFjvSxMVI/fsdjYodPafcFn+fWOmxMH+wwkc8lzmXT6nqc5hgWuqKxhSsKSs6h9HSDWYdlH99ZidOSyfP/6lOlBY/o5VI/1MTJJRYlyCpZi9+ugfvyiCy1vTMHiblHrR5O5dyWqb8SUkqDdAvvDvByz/O5J8My/yrIDu8yg5uybk7xwQUNPoMU/ifdCq+an3Kh8sZNh91bC4GU26LFNbg+unJOHW2W/ztk5+8gzcFogVqjYlsJLIFUadT3g58juBrO+/tQOMKmtqT3w74cQHfdgbcgWxSIKs5De7AMc1zMAGSmYWuFNNhniJ3tNwBag5uyIYb8/vdgZ1p3i8WLLKSaSIe8gFHLAJwjVD+HVKNBjd+cJBKcx99+Dy1dAVDoDKMZQEUkjyCcWTTjqHN7w0NAjkkC3h4gdiFrPBMsHQVU9+yvFO0wOZ2rrn2JeVRFg6AsmrcUtFsjsHJM8QUQjnhrgYy5ModzVTQbg4tSpdPdTge3AQQwwjnFGOYKOZBBUfwWa42QexkcHvDbtcFGBDD2qS5gYqguK5QKpcwnU4HtzGlWH/PimpYjRrP82av6hpPQPFsTCQd/vjHyBz/KegZGAty8PLIMM9VyIrnfo5JKejnWuacEGgOfjLzQjdx5qcqSChX54sYgN8pAdkFa8G+YjQcDe5YQq+2hEnA8mEaO7aJgmjHLr1YHM1i3Rv/NaYq1DoJtXPQSqnTSbTD0U21RyfxLsefLDQ6STTmRCLJ9uLf+LhGe/Jp3Eb8ryQV88MVnpn7U6yTwfJ6dlW9ZOGJtaYcxKQtYsd20uwiejpYsqq5UoReDCxkngKa4qWjocDoY1ymvQHxD+WmpmjKTGE5Oq0DjAb3ffP19xBEUOWcFNLlyGhxxk2VsSOBPbgnX7qaCzVAVvKA+zmDwAw26QTzWlKkmKjRLQfAjONMm06FhiVT0Nj4olCkFudWcJVsSi1uXMHJNE7rMCcV2AP1d/tXkAPQm6/8oGk9w3TwCErCkikgd8pnew7ZFSO1YbxgCl2eiMgSf7yONoTNFM1xxg4sn7DWoBD/Ph9BerfyFEwYuLyjiCQmJ1Fj32PlA7htMAWJTsS3MYwEA6vJnpMYdqMYDH0QtKKswcpDmKjSWJEPdglXKCfK2j9BaPCjZO/cGnhHgsfaVxDWgDSxa3m2oJqDqML3U0mWz7uc4nAkBzv9TMQNGXEYnBS3j2YWV7IIl5vVDsSbPYgAIzqFHwu88p/5LJSWoRE+kfAYfsSu58YROxROmNcUvxrL6JO5cqeYpoJJFC5wHwuN8CZKfYJitjn1MdZQcNzSKFV1Cd0m0jIFlld+3B2OcfRBC8fiJwhGgkCLkZrFrhRWgUKdG/VkkcLJMzgoVqy6jLc8BZZSyTpHU863KFlW0lEuLCmWvyBcithxJKp3flqFgMTiXl8nVhBWwhP4C+CAPZBlwHO3KJgrwF3G2q9HkokmUTnYgrPZiJwqZDHPxy4j6N355BDsoSK6JRBD7joN3DY1qvaOViNwpIFR8AYo8Btot2+2LYUtVat0GbGtwWCjd1yUuBMcbQrnBZ3onDq6nstvu4pkKa4A91o6LYKlVze6gLXo9R21Fr37KIF1S6OOi+8Mc8jPnIvRpVtHi9zD7J7JAN4v+cBTz8MRj8UgDnk+Cg+8eLDcyKml8YGk7IoaXjQvFL+dHphVT9JzWh0toLVNZCXvqTnWgrnCmVUHLl2G4Bax2hE/gdOCqDyw3LFsK3SSh37N/ZMyNC0A3nwagKuXFK5FtRK4WgiZe4XuJYuIO02Rq6VQXLbV9zB3/EIHD/fbOLTUeRDLs0zLLxpuMUrIPcHTzqGFrlwG0nm5XS1xfXcN1ylCr7fZppSra8e7RTzLOErHnf1EZd166aKrJRFmFEJAqTSl88Z2Ei2Tv6IgAyVmOUQeDLUjtXDizVT1nAULRzt9wFhL5ws40QGWoHdVw7FZxcqnJU588piJpLovXfBHZkmC+YByvk3Q5e5Yj8bW4EeJ5gZLIj5IMJC+NAuds4DbyZzr8qOe0S6PS5aOeLAyuduFZZxTxsma7jitB7hlgMfya2xPlWnV/CFDLQlIXzXcwzjicAyiL6Zi+o6KvgLTFimOQRj50C9qqkMgvkpjPzuwp5sC8m9iPCe0KKu1SeHReDp4uma56NkGljTxeVUDu+v0G/ziY+yLurg7niDCbHCSyvtQ+c/TCczRZChZ8w3khxVChq6MpmS8DjdxRDZ7/lCCKnHG3AHLheE9j37UI0mtjrHxrRlphTwSlCPfrsTW4MnD8lRwA0LSM9M2sSU43Qc0xUvoWEzYk8QRJML89YW7Ai4LsViOr7TfcUppCU5zjkuc0GSDhxg8tu45wIkgu8GtwssOB/0mXOcBTQXHbUDDQxTzMpf4I/JjNnEkxYcz3i+9NIrRu+A10B3Jp8OT5E/s8KfraKdmmdAjfiBOpXBZ+k3gdCTofkYHXamfv+KBw2Q3pQt3jk4TWyeJe45U6oO4moRlzyEL+tD928UY73Slklqxwgm7yF/C1Xtb53G5RbJ59GrMyZ50nqhxEb8g4RdGkJRso8/OUjEpktxEUbrHdw264qdFvBSubnBrOCzC78JdQD+jqOOCWEOziP8bDJ3EIe24BtZwVMSDSr3F9LMr2iqivX2UBVt/0/nr7RIedPsF4pcUd6Q93mGDz+nKVRLN9T6Kwz54JY010Ug/ybaGUjI5B3vrT7R6iWKsEV5izXdHU2gNpYyyOGUW7ig+uwEhO/F3HZXFGko51RXWS+onmTr/7vmJphRc7uT9ZO929CKQkosHs/7W/zdVB6TM64WdAhyWtDuflORfqAKw23j/yvB0/3tfKQW8GsV0JAAJ122kPyN9ispzsaf5nDo+ddwURTVv0J4mdetIsXgFX9QVZ4iFm4i5Trr2Mf5GH50/ZFLqpOAAfmPWp0Ve5n144HsEZ5CNhkWyJas7+Dpc4updYjY3Tb4x1pFZpNcpnm9wjkqcaGK/QWcV6Up+2BmEJS0TRAtVbvytCXVqyVVQ+A3mkt6taQjOFF4O8jfvAX1F+WLycA436tsuCwirv5H3sKu3RcoVPNYIdAiTevBD5xZ245gG/D2MwnHBFcVwvHCexkJl5mL67Dnr0VQRzbbkyPLM+INP8iVOR2XmboUfUkp75YisoSLCN+oq99nyTU3dVJ7ltrYf6fb4XvUTVj/ojPrD9UsVYinIFXia6v1hWLKL52O1uZ1r/hr7LNrmx2eX8hGuyzm4TfSDxNsq3MnBU6wMaJpuyy23FMW1f/Dq2j9Lyd08dKyg1xfeBjxgcE0qjbRc5O88qRzXmt2Y2OhnOfI38PI80xwPT+wXD/5RuFNYM1a3iyogwsYyka3Fgr2SMCdcFx4/aPyJxQipugKJB1P8IYX6ubO12MCSq8fRDHHmzQpls5TXQdaPZTT4UWTYhZixW9K31FjDHseyS3TLqijZ67A4PCFoP6p0WsawwB6vYL0GVF0Wgi/KcYm+Khx2bkhYpf/NIWlBrDzdXWnrVtrWZtirwHEOKI7rsWRIFCDgsxziOY8bsqVVbbG1jIqHdg31qERt/jqP1XK5ghAwqrs5m2vuaOlDmeDlItCDv8XUljgfb+/R0VIn7GJ7j9pWCR1jqUZ5bFBtr4XI2xMMQa4v0MhVG9rlhry8klXWcow0zlWs04oVxqQZriWlv9I54yr4DoJHsBl6ZyxcsKtSTHIUuzAvZBfiqcCqlDnTCmjFhbTS1B1Wmko7yeYJfndogmrpaL6lnG+fEw8ufew8l3kmokKqYRFcq4ws1lJVAXYJEDDbUXUuKkCnFsgnutrarW3dpiOuFok1PWD5WywekH2ih+ijxky6WgLkykBkDV/BpWeNB+GNGuxOq2BxXrXYE4jTdQFkGToeVqD5svF8wZKX7Xb8Wmx1BGOzQsMNffHOYNOCjEdN8CW6Tlc0wb/xkiHMNVTwVhNefYy+283+KYpElJ1DWFJls7/BVjM4p4lu7R/yKf0K0K0Af/mvYgCNm9d4XEHV77C1xmxckMN8rRaWUFeba8mTF9ZYSV2rRz7RMveypzTY7DHJ4gXRkep9Ep+frCLNgZeChY23eFCH98N5hfhnCBa/77GRNRkN8H3toP4CkIhIRIv8kZs1sQbP/Om7OI4SHjRd+Tv2r68sggicSCykif2UVQqioeDj4lPkF8rPrInNyYoVksXjqnqgM3i+xqTQ41Y75Mo8FB9Fxebu4NfNT4M96+1fLv0DO36ll+uHhfEHe90Cd074hD9z55nGee9nW5Nxj86+81K3NZkMXmZrRM1JIgwVBdmWhrw6D1MFyGCn5r9Xl2CYtQVpvCVH5bbnrmDWU06HNZTyga9T6zI1JXhB0s0eP8Mvq3cVNFKgGvuK0jT7RxPUUlAsqs1lJ04P1W6E4vs82Fi8V69eNWsgciSRUE2d0GQHTOKWcK4cj6pYsErmKjJ8BwZzruy8q6n5uNL81GQrEdOCyRvpzf3x7a0JreTtWhgLnnTY+vKpAO1HlcH2UEkWezROPI3U1Nisa5x7P6kBpmTpBhxWNF1stjHZE4GLo6tVqkglSrKvnERg9T/+ZvGcU6CGKbaHSrLuwm3GNiownFGIT35UtsgqWomTKgCFrYG99sWPFQUEa0STNuWwh65mSvH1ha3yiattlSCBlWKBWrsc2UMlR7nb9nvy2tRcCU7+FSn2QtgvEnxQUYvUgDaHGv3JdALcv4vs2NTczDUXD5EVvNsqQomNeID9OpS3K1N8OZq/s9kEVpLDG6+icHtq+kwlI2swzuLXBHeqcoxQhSoB0RqrReLERCqRqL9W24BSwiHSX/L+qnh7ogmmRIRdMPzkVkb1m7sT1kQw1QTs9m7xvdGm4Y6GRVjhvlwDxCxCrkFDRZWQv3nPjq16NhoVwUyq5/Cd7+isLuH/m4BWCchMVSHcPjFsu5agTQJGThECtv7iMexgH0duCZiljX6JPRoXG+ODwuzEsH1skyLq7xBhqwxDtXVJOp6yTj6DbZXEQxokCCsN8YJvE7IkJXlZbnU2bKskIi9khy5K22RYIBxPzA1DDwqfwVIt227r2pYtceKue0eYI2DsinC5tvMU2JVgfQdaXksvb3ftRGNFhMVT7AAmzynf7uzENdFcx4hX87MrxviF3RimgkGcMqBaixOQTnh7KPE+xJ4JfAt7TwtsLZ51FbIYp5hMwaQrmisi104wkgSy5vMiV/WZq/nsRCZFE6PUN/6KcCHoEIa6G5ldJeO3Jm6w0KQThVOlUFNes820k7l1ZHhHtlpHfopqXKXKuYTiH86J4l4qYk+qpCqV03FcUq7vsyD138jBD75yLUVwijrTdREdKensVEQYVG5Lug3JkQLea4IdKdX6t3jBP6PdddyxaihUaN6Nwq6huKLHqOu3S/EVp+BqYZlPhs47XuPrRiWFV1Z9FN566ICXEsvb4Scl7Bl8n3RTRWdSIBD/uisviX7j74yy+9TdzNb/Aw=="}),
			    Source = Csv.Document(Binary.Decompress(Binary.FromText(Packed, BinaryEncoding.Base64), Compression.Deflate), [Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Blanks = Table.ReplaceValue(Headers, "", null, Replacer.ReplaceValue, Table.ColumnNames(Headers)),
			    Typed = Table.TransformColumnTypes(Blanks, {{"service_key", Int64.Type}, {"service_name", type text}, {"agency", type text}}, "en-CA")
			in
			    Typed
