(()=>{'use strict';const D=window.PROJECT_DATA,M=window.Metrics,$=id=>document.getElementById(id),n=v=>new Intl.NumberFormat('en-CA',{maximumFractionDigits:1}).format(v),days=v=>v===null?'—':n(v),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const serviceMap=new Map(D.services.map(s=>[s.id,s]));let selected=[],current,page='overview';
const monthLabel=m=>new Date(m+'-02T12:00:00').toLocaleDateString('en-CA',{month:'short',year:'numeric'});
for(const m of [...new Set(D.cells.map(c=>c.month))].sort())$('month').add(new Option(monthLabel(m),m));
for(const s of D.services)$('service').add(new Option(s.name+' · '+s.agency,s.id));
$('snapshot').textContent='Source snapshot '+D.manifest.as_of_date;
$('provenance').textContent='Downloaded '+D.manifest.retrieved_at_utc.slice(0,10)+' · '+n(D.manifest.row_count)+' source records. Refreshing this page does not fetch new data.';
function bars(id,items,shade='#087d77'){const max=Math.max(...items.map(x=>x.value),1);$(id).innerHTML=items.length?items.map(x=>`<div class="bar-item"><div class="bar-label"><span title="${esc(x.label)}">${esc(x.label)}</span><strong>${n(x.value)}</strong></div><div class="track"><div class="bar" style="width:${x.value/max*100}%;background:${shade}"></div></div></div>`).join(''):'<p class="empty">No requests in this selection.</p>';}
function columns(id,items){const w=580,h=225,left=48,top=28,bottom=36,plotH=h-top-bottom,plotW=w-left-12,max=Math.max(...items.map(x=>x.value),1),step=plotW/items.length,bw=step*.57;let out=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(items.map(x=>x.label+': '+n(x.value)).join('; '))}">`;for(let i=0;i<4;i++){const y=top+plotH*i/3;out+=`<line x1="${left}" x2="${w-8}" y1="${y}" y2="${y}" stroke="#e6ece7"/><text x="${left-8}" y="${y+4}" fill="#73817f" font-size="10" text-anchor="end">${n(max*(1-i/3)/1000)}k</text>`;}items.forEach((x,i)=>{const bx=left+step*i+(step-bw)/2,barh=x.value/max*plotH;out+=`<rect x="${bx}" y="${top+plotH-barh}" width="${bw}" height="${Math.max(barh,0)}" rx="3" fill="#087d77"><title>${esc(x.label)}: ${n(x.value)}</title></rect><text x="${bx+bw/2}" y="${h-11}" fill="#617571" font-size="10" text-anchor="middle">${esc(x.label)}</text>`;});$(id).innerHTML=out+'</svg>';}
function serviceRows(){const groups=new Map();for(const c of selected){if(!groups.has(c.service))groups.set(c.service,[]);groups.get(c.service).push(c);}return [...groups].map(([id,cells])=>({service:serviceMap.get(id),...M.aggregate(cells)}));}
function render(){selected=D.cells.filter(c=>($('month').value==='all'||c.month===$('month').value)&&($('service').value==='all'||c.service===+$('service').value));current=M.aggregate(selected);const a=current;
$('selection-count').textContent=n(a.total)+' source records selected';
const kpis=[['Requests',n(a.operational),'',n(a.duplicates)+' duplicate records excluded'],['Open at snapshot',n(a.open),'',n(a.open30)+' open for 30+ days'],['Median closure',days(a.median),'days','Valid closed records only'],['90th percentile',days(a.p90),'days','90% of valid closures at or below'],['Valid closure sample',n(a.closureSample),'','From '+n(a.closed)+' Closed records']];
$('kpis').innerHTML=kpis.map(([label,value,unit,detail])=>`<article class="kpi"><p class="kpi-label">${label}</p><p class="kpi-value">${value}<span class="kpi-unit">${unit}</span></p><div class="kpi-detail">${detail}</div></article>`).join('');
const groups=serviceRows(),monthGroups=new Map();for(const c of selected)monthGroups.set(c.month,(monthGroups.get(c.month)||0)+c.total-c.duplicates);
columns('monthly-chart',[...monthGroups].sort().map(([m,value])=>({label:monthLabel(m).split(' ')[0],value})));
bars('channel-chart',Object.entries(a.channels).sort((a,b)=>b[1]-a[1]).map(([label,value])=>({label,value})));
bars('service-chart',groups.sort((a,b)=>b.operational-a.operational).slice(0,8).map(g=>({label:g.service.name,value:g.operational})));
columns('weekday-chart',['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((label,i)=>({label,value:a.weekdays[i]})));
const bands=[['0–7 days',0,7],['8–14 days',8,14],['15–29 days',15,29],['30–59 days',30,59],['60–89 days',60,89],['90+ days',90,Infinity]];
bars('age-chart',bands.map(([label,lo,hi])=>({label,value:[...a.ages].filter(([d])=>d>=lo&&d<=hi).reduce((s,[,c])=>s+c,0)})),'#b66a22');
$('closure-sample').textContent=`This selection includes ${n(a.closureSample)} valid closed records and ${n(a.open)} open records. Median open age: ${days(a.medianAge)} days.`;
$('workload-table').innerHTML=groups.sort((a,b)=>b.open-a.open||b.operational-a.operational).slice(0,15).map(g=>`<tr><td>${esc(g.service.name)}<br><small>${esc(g.service.agency)}</small></td><td>${n(g.operational)}</td><td>${n(g.open)}</td><td>${n(g.open30)}</td><td>${days(g.median)} days</td><td>${days(g.p90)} days</td></tr>`).join('')||'<tr><td colspan="6">No requests in this selection.</td></tr>';
const checks=[['All source records',a.total,'Before duplicate exclusion'],['Explicit duplicate records',a.duplicates,'Excluded from operational measures'],['Nonduplicate records',a.operational,'Included in request volume'],['Closed records with missing closure date',a.quality.missing_closed||0,'Excluded from closure-time measures'],['Invalid closure dates',a.quality.invalid_closed||0,'Earlier than submission, after snapshot, or unreadable'],['Invalid submission dates',a.quality.invalid_requested||0,'Flagged; build checks the submission cohort'],['Missing community code',a.quality.missing_comm_code||0,'Retained in an Unknown community group'],['Unrecognised statuses',a.quality.unknown_status||0,'Retained and flagged'],['Open records with closure date',a.quality.open_with_closed||0,'Open status retained; excluded from closure-time measures']];
$('quality-table').innerHTML=checks.map(([label,value,meaning])=>`<tr><td>${label}</td><td>${n(value)}</td><td>${meaning}</td></tr>`).join('');
window.DASHBOARD_STATE={month:$('month').value,service:$('service').value,total:a.total,operational:a.operational,open:a.open,duplicates:a.duplicates,median:a.median,p90:a.p90,closureSample:a.closureSample,page};
}
function setPage(next){page=next;document.querySelectorAll('.report-page').forEach(e=>e.hidden=e.id!==page);document.querySelectorAll('nav button').forEach(e=>{e.classList.toggle('active',e.dataset.page===page);if(e.dataset.page===page)e.setAttribute('aria-current','page');else e.removeAttribute('aria-current');});const titles={overview:['Understand the demand.<br>See the open workload.','A view of service requests submitted from January to September 2026.'],workload:['See what remains open.','Age and category detail for requests still open at the source snapshot.'],quality:['Trust starts with definitions.','Understand the source, exclusions and limits behind every measure.']};$('page-title').innerHTML=titles[page][0];$('page-description').textContent=titles[page][1];render();}
document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>setPage(b.dataset.page)));$('month').addEventListener('change',render);$('service').addEventListener('change',render);$('reset').addEventListener('click',()=>{$('month').value='all';$('service').value='all';render();});
$('export').addEventListener('click',()=>{const rows=[['Measure','Value'],['Submission month',$('month').value],['Service category',$('service').selectedOptions[0].text],['Snapshot date',D.manifest.as_of_date],['Source records',current.total],['Duplicate records',current.duplicates],['Nonduplicate requests',current.operational],['Open at snapshot',current.open],['Median closure days',current.median??''],['P90 closure days',current.p90??''],['Valid closure sample',current.closureSample],['Open 30+ days',current.open30]];const csv=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),link=document.createElement('a');link.href=url;link.download='calgary-311-selection.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});render();})();
